version: '3.8'
services:
  fastapi:
    image: shounnnn/fastapi:dev
    ports:
      - "8000:8000"
    # volumes:
    #   - ./app:/code/app
    networks:
      - network
    restart: always

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - network
    restart: always
    command: --interval 30 --cleanup

networks:
  network:
