version: '3.8'
services:
  fastapi:
    image: shounnnn/fastapi:dev
    ports:
      - "8000:8000"
    # volumes:
    #   - ./app:/code/app
    networks:
      - network

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - network

networks:
  network:
